### ISSUE TITLE
Conjuntos y Relaciones

### ISSUE THREAD

**Issue by Anais-droid** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Anais-droid#2]
[Mapa Mental Lluvia de Ideas Colorido Verde (2).pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Anais-droid/files/12826502/Mapa.Mental.Lluvia.de.Ideas.Colorido.Verde.2.pdf)

**Comment by josealfredo79** [comment]
Calificacion...

**Comment by LuisAlexisMorales** [comment]
Manejo conceptual: 25%
Relación entre concepto:22%
Calidad de la presentación:25%
Gerarquia:22%
Total:94%. CalFinal:18.8

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
